apiVersion: "kubernetes-misc.xyz/v1"
kind: CronHPA
metadata:
  name: scale-down
spec:
  cronSpecSeconds: "30 * * * * *"
  scaleTargetRef:
    apiVersion: "extensions/v1beta1"
    kind: "deployment"
    name: "worker"
  HorizontalPodAutoScaler:
    name: "worker"
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 60
---
apiVersion: "kubernetes-misc.xyz/v1"
kind: CronHPA
metadata:
  name: scale-up
spec:
  cronSpecSeconds: "0 * * * * *"
  scaleTargetRef:
    apiVersion: "extensions/v1beta1"
    kind: "deployment"
    name: "worker"
  HorizontalPodAutoScaler:
    name: "worker"
    minReplicas: 4
    maxReplicas: 8
    targetCPUUtilizationPercentage: 40
