apiVersion: "kubernetes-misc.xyz/v1"
kind: kudec
metadata:
  name: example
  namespace: team1
spec:
  days: 365
  countryName: ZA
  stateName: GP
  localityName: JHB
  organizationName: Kubernetes Misc
  organizationalUnit: Orbital Kinetic Weapons Platforms
  injectedSecrets:
    - namespace: team1
      secretName: secret-key
      sourceKey: private
      keyName: private
    - namespace: team2
      secretName: secret-pub
      sourceKey: public
      keyName: public
