kind: ServiceAccount
apiVersion: v1
metadata:
  name: kudecs-svc-acc
  namespace: kudecs
automountServiceAccountToken: true
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kudecs
  name: kudec-clusterrole
rules:
  - apiGroups: ["", "extensions", "kubernetes-misc.xyz"]
    resources: ["namespaces", "secrets", "kudecs"]
    verbs: ["get", "list", "watch", "update", "create", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kudec-clusterrole-binding
  namespace: kudecs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kudec-clusterrole
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: kudecs-svc-acc
    namespace: kudecs