kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kudec-clusterrole
rules:
  - apiGroups: ["", "extensions"]
    resources: ["nodes", "services", "endpoints", "namespaces", "ingresses", "pods", "secrets", "kudecs.kubernetes-misc.xyz"]
    verbs: ["get", "list", "watch", "update", "create", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kudec-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kudec-clusterrole
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: bigip-ctlr
    namespace: <controller_namespace>